### ISSUE TITLE
Flush stdout in perprop

### ISSUE THREAD

**Issue by james9909** [trailofbits/echidna#120]
This would allow other programs to parse the stdout from perprop as a stream, as opposed to receiving all the stdout when the program exits. Since it may take a while for perprop to finish testing a single property, I think this would be good to have.

**Comment by ggrieco-tob** [comment]
Can you try branch [dev-flush-stdout](https://github.com/trailofbits/echidna/tree/dev-flush-stdout) ?

**Comment by james9909** [comment]
Works great for me
