### ISSUE TITLE
Docker image fails to build

### ISSUE THREAD

**Issue by james9909** [trailofbits/echidna#144]
The echidna Dockerfile specifies `ubuntu:rolling` (which is Ubuntu 18.10 atm), but the Ethereum ppa doesn't currently have any `solc` packages for that version. Because of this, [new docker builds of echidna fail](https://hub.docker.com/r/trailofbits/echidna/builds/bp8dg35wdpkbf7tuffytfyk/).

**Comment by asymmetric** [comment]
Closed in #148.

**Comment by james9909** [comment]
Docker hub still [fails to build the container](https://hub.docker.com/r/trailofbits/echidna/builds/bqmvsa7kawzqvasw56zsfhw/).

**Comment by asymmetric** [comment]
> Missing (or bad) C library: secp256k1

**Comment by ggrieco-tob** [comment]
This was already fixed.
