### ISSUE TITLE
Configured contract address not honored

### ISSUE THREAD

**Issue by asymmetric** [trailofbits/echidna#147]
Given the following contract:

```
pragma solidity ^0.4.24;

contract Foo {
    function bar() {}

    function echidna_address() returns (bool) {
        return address(this) == 0x00a329c0648769A73afac7F9381E08Fb43DBeA74;
    }
}
```

and this config file

```
contractAddr: 0x00a329c0648769A73afac7F9381E08Fb43DBeA74
```

I would expect the suite to pass, whereas I get 

```
━━━ foo.sol ━━━
  ✗ "echidna_address" failed after 1 test.

    │ Call sequence: bar();

  ✗ 1 failed.
```

**Comment by ggrieco-tob** [comment]
Can you retest with the `dev-no-hedgehog` branch? I think that's is fixed in that branch.

**Comment by asymmetric** [comment]
I tried `stack build` on that branch, but it failed with:

```

**Comment by asymmetric** [comment]
Managed to use Docker to build the branch (at commit a67091f499b90c9ae874e553c67e28798fc8457f), got this error:

```
Failed property "echidna_address"
Original input:
bar() by a329c0648769a73afac7f9381e08fb43dbea70
Original events:
[]
Reduced input:
bar() by a329c0648769a73afac7f9381e08fb43dbea70
Reduced events:
[]
```

**Comment by ggrieco-tob** [comment]
Uhm. I will take a look to this issue then. That branch is where we are doing the refactoring. 

Do you have a use case for this feature?

**Comment by ggrieco-tob** [comment]
Hi @asymmetric, can you check #178 ?

**Comment by ggrieco-tob** [comment]
This is fixed in `master`. Please reopen if it fails for you.
