### ISSUE TITLE
Nonzero return code on failure?

### ISSUE THREAD

**Issue by mrice32** [trailofbits/echidna#160]
Is it possible to get the echidna-test binary to give a pass back a nonzero return code when any properties fail? If this is not currently possible, it would be really nice to have this for use in CI.

**Comment by incertia** [comment]
58b6858 adds this, which should be merged soon (tm)

**Comment by mrice32** [comment]
Thank you!

**Comment by ggrieco-tob** [comment]
This should be fixed.
