### ISSUE TITLE
README is a 404 for example config and documentation

### ISSUE THREAD

**Issue by jMyles** [trailofbits/echidna#167]
The line in question is [this one](https://github.com/trailofbits/echidna/blame/c06a9da7f9f8312e3c166b88b1d4a3d1d4c208ca/README.md#L42):

`The configuration file allows users to choose EVM and test generation parameters. An example config file, along with documentation, can be found at [solidity/config.yaml](solidity/config.yaml).`

This might be a repeat of #95, though `5a574f7b34814925be26d58142c533d1f8a41927`, the last commit to amend this line, was merged months later.

We need config docs!

**Comment by ggrieco-tob** [comment]
Oh, sorry!. We should fix this very soon: yesterday, we started a PR to fix the README and update documentation and examples, here #168.

**Comment by ggrieco-tob** [comment]
A preliminary version of the configuration options documentation is available here: https://github.com/trailofbits/echidna/wiki/Config

**Comment by ggrieco-tob** [comment]
@jMyles can you take a look to #168?
