### ISSUE TITLE
please help me on running echidna

### ISSUE THREAD

**Issue by erfanwakka** [trailofbits/echidna#187]
I cannot print the report
I simply want to test an example but when It's says `Campaign complete, C-c or esc to print report `
I do esc and nothing happen

**Comment by ggrieco-tob** [comment]
is ctrl+c also failing?

**Comment by ggrieco-tob** [comment]
Feel free to stop by our [Slack channel](https://empirehacking.slack.com/messages/C7KKY517H/) for help using Echidna.

**Comment by erfanwakka** [comment]
could you send me an invitation : andesta.erfan@gmail.com
