### ISSUE TITLE
gitter or riot channel

### ISSUE THREAD

**Issue by snd** [trailofbits/echidna#19]
a gitter or riot channel for discussion around echidna would be useful

**Comment by ggrieco-tob** [comment]
We are using #ethereum in [Empire Hacking](https://empirehacking.slack.com). I should update the README.

**Comment by snd** [comment]
i joined empirehacking.slack.com but the #ethereum channel doesn't seem to be public. could you invite me? i'm `max`. probably makes sense to make #ethereum public so it's easier for others to join

**Comment by dguido** [comment]
It's public and you appear to already be in the channel.

**Comment by snd** [comment]
right. was confused by slack there for a second

**Comment by snd** [comment]
@dguido could you leave this open as a reminder to add it to the readme?

**Comment by dguido** [comment]
https://github.com/trailofbits/echidna/commit/0debf87edd23dc2488683584324a66bb808a1b32
