### ISSUE TITLE
test specific contract in file

### ISSUE THREAD

**Issue by snd** [trailofbits/echidna#23]
right now `echidna-test` loads the first contract in a file and tests it.

this is inflexible and doesn't work well with `import`s as they appear to echidna as the first contracts in a file.

**modify `echidna-test` and `loadSolidity` to take `contract-name` as optional second argument**

this would open up a useful pattern where one writes a contract as usual without any echidna related modifications and then inherits a test contract from it that contains the echidna properties and a constructor with 0 params that does the required initialization (see https://github.com/trailofbits/echidna/issues/15).

right now this is not possible since the unmodified contract that is inherited from must come first.

**Comment by japesinator** [comment]
this is absolutely a better design decision than what we do now, I'm going to take a look at getting some kind of progress on multi-contract stuff made this weekend

**Comment by snd** [comment]
going to dig into the echidna source this weekend. wrote a bunch of haskell some years ago and it's still one of my favorite languages. i hope to contribute soon

**Comment by japesinator** [comment]
let me know if you have any questions! I'm this same nick on the [empire hacking slack](http://empireslacking.herokuapp.com/)

**Comment by snd** [comment]
got this working. will do a PR tomorrow

**Comment by japesinator** [comment]
awesome!
