### ISSUE TITLE
Allow to specify which user calls each method in a contract

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/echidna#30]
Some smart contracts define an address as "owner" to perform certain "privileged" operations. For instance:

```solidity
contract C {
  uint state = 1;
  address owner;

  function C() {
     owner = msg.sender;
  }

  function only_owner(uint x) public {
      require(msg.sender == owner);
      state = x;
  }

  function echidna_test() public returns (bool) {
      return (state == 1);
  }
}
```

Unfortunately, Echidna does not allow to specify the use of different users (contract owner, user, attacker) when the transactions are executed. It could be nice to have a command line option for that.

**Comment by japesinator** [comment]
This is pretty easy to fix when API scripting, just write some `MonadGen m => m Address` that picks from a list of addresses you care about, then add `state . caller .= a` where `a` is the result of that generator to your `Action`s.

Totally open to adding it to the CLI, and it shouldn't be all that hard, but unsure what API to use. Thoughts? If someone submits an RFP or whatever, I'll try to get it done this weekend.

**Comment by ggrieco-tob** [comment]
So one possible approach to start is to use a value generator that produces the address to  use as caller in the EVM transaction. For instance, the signature of `execCall` could be:

```haskell
execCall :: MonadState VM m => (Address, SolCall) -> m VMResult
```

What do you think?

**Comment by ggrieco-tob** [comment]
This is already implemented in echidna and perprop.
