### ISSUE TITLE
echidna_* Functions in separate solidity file

### ISSUE THREAD

**Issue by rbharath** [trailofbits/echidna#60]
I'm trying to figure out how to use Echidna to fuzz test some TCR contracts. For example,

https://github.com/computablelabs/computable/blob/master/contracts/Registry.sol

I'd prefer not to add on `echidna_*` functions into these contracts since that would make these contracts different from the canonical TCR contracts. Would there be a way I could make a separate file, say `echidna_registry.sol` and have all my new functions for fuzz testing in there without modifying the original `Registry.sol` file?

**Comment by japesinator** [comment]
Usually what I do there is have a test contract inherit from Registry, can that work for your case?

**Comment by rbharath** [comment]
Will give this a try and report back here.

**Comment by japesinator** [comment]
Did this work for you?

**Comment by rbharath** [comment]
We haven't had a chance to implement this yet. But have opened an issue https://github.com/computablelabs/computable/issues/70 to coordinate.

**Comment by japesinator** [comment]
Closing unless it becomes an issue w/ the strategy described above
