### ISSUE TITLE
Fuzzing doesn't sufficiently cover different addresses for a transfer

### ISSUE THREAD

**Issue by albrow** [trailofbits/echidna#61]
Consider the following simplified token smart contract:

```solidity
pragma solidity ^0.4.24;

contract TokenTest {
    mapping (address => uint) public balances;
    address[] private addresses;

    constructor () public {
        balances[msg.sender] = 10000;
        addresses.push(msg.sender);
    }

    function transfer(address to, uint256 amount) public returns (bool success) {
        if (balances[msg.sender] < amount) return false;
        // Simulate a bug by commenting out this line. We expect the total number of tokens 
        // in circulation will increase because we forgot to subtract amount from the sender's balance.
        // balances[msg.sender] -= amount;
        balances[to] += amount;
        addresses.push(msg.sender);
        addresses.push(to);
        return true;
    }

    function echidna_totalCannotChange() public returns (bool) {
        uint256 total = 0;
        for (uint i = 0; i<addresses.length; i++) {
            total += balances[addresses[i]];
        }
        return total == 10000;
    }
}
```

I would expect `echidna_totalCannotChange` to fail after a trivial call sequence (calling `transfer` once with any arbitrary values). However, to my surprise, when I run `echidna-test` it passes.

If I comment out the line `if (balances[msg.sender] < amount) return false;` then the test fails as expected. What I can gather from this is that when echidna generates addresses for calling `transfer`, it never tries the address which created the contract (`msg.sender` in the constructor). Therefore, `transfer` never actually works and no tokens change hands. Is there any way to improve echidna so that it can catch bugs like the one in the contract above?

**Comment by ggrieco-tob** [comment]
For fuzzing with addresses as inputs, consider using the improved-addr-gen branch while we think how to integrate this feature into master.

**Comment by japesinator** [comment]
Duplicate of #66

**Comment by asymmetric** [comment]
I just tried running this contract with both scenarios (lined commented out and not) and they both passed.

Seems like the bug which should've been fixed is still there.
