### ISSUE TITLE
Figure out what versions of solc are supported

### ISSUE THREAD

**Issue by japesinator** [trailofbits/echidna#8]
apparently 0.4.21 is not

**Comment by skirmantasjanuskas** [comment]
> Version: 0.4.21+commit.dfe3193c.Darwin.appleclang 
works fine here

**Comment by japesinator** [comment]
huh, I just got a complaint it didn't. once I'm back in NYC, I'll just try all of them starting 6 months ago and actually make a record of how it goes

**Comment by ggrieco-tob** [comment]
> Version: 0.4.21+commit.dfe3193c.Linux.g++

works fine in Ubuntu Ubuntu 16.04.3 LTS

**Comment by japesinator** [comment]
I've never actually had a version of solc fail IRL, so closing until this becomes an issue for someone
