### ISSUE TITLE
Echidna command-line fails on Debian

### ISSUE THREAD

**Issue by yoavw** [trailofbits/echidna#9]
It fails with the following error:

`
# ~/.local/bin/echidna-test solidity/cli.sol 
echidna-test: <stdout>: commitBuffer: invalid argument (invalid character)
`
`
# uname -a
Linux core 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux
`

(we talked about this at the workshop at ETHCC)

**Comment by japesinator** [comment]
This looks like some kind of a locale issue that's causing echidna to choke when trying to print UTF-8. Can you try with the below code for `Main.hs`?

```
{-# LANGUAGE LambdaCase #-}

module Main where

import GHC.IO.Encoding (setLocaleEncoding, utf8)
import Hedgehog hiding (checkParallel)
import Hedgehog.Internal.Property (GroupName(..), PropertyName(..))
import System.Environment         (getArgs)

import Echidna.Exec
import Echidna.Solidity

main :: IO ()
main = setLocaleEncoding utf8 >> getArgs >>= \case
  []  -> putStrLn "Please provide a solidity file to analyze"
  f:_ -> do
    (v,a,ts) <- loadSolidity f
    let prop t = (PropertyName $ show t, ePropertySeq v a (`checkETest` t) 10)
    _ <- checkParallel . Group (GroupName f) $ map prop ts
    return ()
```

**Comment by yoavw** [comment]
Unfortunately I no longer have the machine where it occurred.  I'll try to reproduce it on another host and let you know.

**Comment by hiqua** [comment]
No problem for me on Debian Stretch.

**Comment by japesinator** [comment]
I'm gonna close for now as I'm unable to reproduce. If this happens again, try the code I linked and lmk how it works, I'll modify the actual codebase based on that.

**Comment by lazzarello** [comment]
I can reproduce this. It's a quick fix regarding locales. I'll put together a PR for the Dockerfile and some doc updates, since it isn't a problem with the application code.

**Comment by lastperson** [comment]
I have this same problem with the following contract:
```
pragma solidity 0.4.16;

contract EchidnaBT {
    bool public val = true;

    function set(bool _val) public {
        val = _val;
    }

    function echidna_test() public returns(bool) {
	    return val;
    }
}
```
with latest echidna docker container, on Ubuntu 18.04. Any suggestions?
