### ISSUE TITLE
Gas usage tester leaks a lot of memory

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/echidna#94]
If you run the gas usage tester (#86) with this simple solidity contract:

```solidity
contract TEST {
  function init(address[] _xs, uint256[] _ys) {
        return;
  }
  function echidna_true() returns (bool) {
	return true;
  }
}
```

It will cause a major memory leak. Be careful if you try to reproduce this issue, since it can produce a large amount of swapping and crash other programs (e.g. internet browsers)

**Comment by blperez01** [comment]
Interestingly, this test takes a _very_ long time to run on `echidna-test` even though it doesn't cause a memory leak there
